version: "3.7"

services:
  node:
    image: node:alpine
    container_name: nodejs
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./back:/home/node/app
    expose:
      - "8000"
    command: bash -c "npm start"
    networks: 
      - api

  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks: 
      - api

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
    networks: 
      - api 

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - api

networks: 
  api:
    driver: bridge