version: "3.7"

services:
  node:
    image: node:alpine
    container_name: nodejs
    env_file: .env
    environment:
      - NODE_ENV=${NODE_ENV}
    volumes:
      - ./back:/usr/app
    working_dir: /usr/app
    ports:
      - 3001:3001
    command: npm start
    networks: 
      - api

  mongo:
    image: mongo
    container_name: mongodb
    env_file: .env
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    networks: 
      - api

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    env_file: .env
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_ADMIN_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_ADMIN_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:${ME_DEFAULT_PORT}/
    depends_on:
      - mongo
    networks: 
      - api 

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    env_file: .env
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - api

networks: 
  api:
    driver: bridge